export   const buttons = [
    {
        id:1,
        text:'(',
        type:"symbol",
    },
    {
        id:2,
        text:')',
        type:"symbol",
    },
    {
        id:3,
        text:'ans',
        type:"operation",
    },
    {
        id:4,
        text:'del',
        type:"operation",
    },
    {
        id:5,
        text:'clear',
        type:"operation",
    },{
        id:6,
        text:'7',
        type:"number",
    },{
        id:7,
        text:'8',
        type:"number",
    },{
        id:8,
        text:'9',
        type:"number",
    },{
        id:9,
        text:'%',
        type:"symbol",
    },{
        id:10,
        text:'√',
        type:"symbol",
    },{
        id:11,
        text:'4',
        type:"number",
    },{
        id:12,
        text:'5',
        type:"number",
    },{
        id:13,
        text:'6',
        type:"number",
    },{
        id:14,
        text:'x',
        type:"symbol",
    },{
        id:15,
        text:'÷',
        type:"symbol",
    },{
        id:16,
        text:'1',
        type:"number",
    },{
        id:17,
        text:'2',
        type:"number",
    },{
        id:18,
        text:'3',
        type:"number",
    },{
        id:19,
        text:'+',
        type:"symbol",
    },{
        id:20,
        text:'-',
        type:"symbol",
    },{
        id:21,
        text:'.',
        type:"symbol",
    },{
        id:22,
        text:'0',
        type:"number",
    },{
        id:23,
        text:' ±',
        type:"symbol",
    },{
        id:24,
        text:'=',
        type:"operation",
    },
]